# Generated by Django 2.2.5 on 2020-02-26 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='赞')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('replynum', models.IntegerField(default=0, verbose_name='回复数')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('pic', models.CharField(max_length=255, null=True, verbose_name='图片')),
            ],
            options={
                'verbose_name': '树洞',
                'verbose_name_plural': '树洞',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, verbose_name='open_id')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='用户昵称')),
                ('gender', models.PositiveIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('avatarurl', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='头像')),
                ('province', models.CharField(max_length=20, null=True, verbose_name='省')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='城市')),
                ('session_key', models.CharField(max_length=64, null=True, verbose_name='session_key')),
                ('cookie_key', models.CharField(max_length=64, null=True, verbose_name='cookie_key')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='WishBottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.CharField(default='', max_length=255)),
                ('picker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picker', to='api.User', verbose_name='捡到的人')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='api.User', verbose_name='作者')),
            ],
            options={
                'verbose_name': '心愿瓶',
                'verbose_name_plural': '心愿瓶',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='WishReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.CharField(max_length=255)),
                ('replyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='回复者')),
                ('wishbottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WishBottle', verbose_name='心愿瓶')),
            ],
            options={
                'verbose_name': '心愿瓶回复',
                'verbose_name_plural': '心愿瓶回复',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='TreeHoleReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.CharField(default='', max_length=255, verbose_name='内容')),
                ('answered_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='回复者')),
                ('treehole_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TreeHole', verbose_name='树洞')),
            ],
            options={
                'verbose_name': '树洞回复',
                'verbose_name_plural': '树洞回复',
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='treehole',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='作者'),
        ),
        migrations.CreateModel(
            name='SysMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('flag', models.BooleanField(default=False, verbose_name='已读')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统消息',
                'verbose_name_plural': '系统消息',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('open_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='用户')),
                ('treehole_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TreeHole', verbose_name='树洞编号')),
            ],
            options={
                'verbose_name': '赞',
                'verbose_name_plural': '赞',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('open_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='用户')),
                ('treehole_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TreeHole', verbose_name='树洞编号')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-time'],
            },
        ),
    ]
