# Generated by Django 2.2.5 on 2020-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmsg',
            name='content',
            field=models.TextField(default='', max_length=255, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='treehole',
            name='content',
            field=models.TextField(default='', max_length=255, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='treeholereply',
            name='content',
            field=models.TextField(default='', max_length=255, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='wishbottle',
            name='content',
            field=models.TextField(default='', max_length=255, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='wishreply',
            name='content',
            field=models.TextField(default='', max_length=255, verbose_name='内容'),
        ),
    ]
