# Generated by Django 2.2.5 on 2020-02-27 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200226_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='writer_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='becollected', to='api.User', verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='writer_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='beliked', to='api.User', verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collect',
            name='open_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collecter', to='api.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='like',
            name='open_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='api.User', verbose_name='用户'),
        ),
    ]
