# Generated by Django 2.2.5 on 2020-02-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200227_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='writer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='becollected', to='api.User', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='like',
            name='writer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beliked', to='api.User', verbose_name='作者'),
        ),
    ]
