# Generated by Django 2.2.5 on 2020-02-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200227_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='writer_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='writer_id',
        ),
    ]
